services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest_server
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_ssr_client
    environment:
      API_SERVER_HOST: server
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      - server

volumes:
  postgres_data:
